@startuml
scale 800 width

[*] --> ChoosingWeddingPhaseState

state ChoosingWeddingPhaseState {
  [*] --> ChoosingPhase
  ChoosingPhase --> PhaseSelected : selecting phase
}

ChoosingWeddingPhaseState --> CreatingNewlywedState : 1. Create newlyweds
CreatingNewlywedState --> ChoosingWeddingPhaseState : [done]

ChoosingWeddingPhaseState --> ChoosingWeddingPlaceState : 2. Choose place
ChoosingWeddingPlaceState --> ChoosingWeddingPhaseState : [done]

ChoosingWeddingPhaseState --> ChoosingFianceeDressState : 3. Choose fiancee dress
ChoosingFianceeDressState --> ChoosingWeddingPhaseState : [done]

ChoosingWeddingPhaseState --> ChoosingGroomDressState : 4. Choose groom dress
ChoosingGroomDressState --> ChoosingWeddingPhaseState : [done]

ChoosingWeddingPhaseState --> ChoosingRingState : 5. Choose rings
ChoosingRingState --> ChoosingWeddingPhaseState : [done]

ChoosingWeddingPhaseState --> ChoosingWeddingMenuState : 6. Choose menu
ChoosingWeddingMenuState --> ChoosingWeddingPhaseState : [done]

ChoosingWeddingPhaseState --> GuestInvitationState : 7. Invite guests
GuestInvitationState --> ChoosingWeddingPhaseState : [done]

ChoosingWeddingPhaseState --> CeremonyState : 8. Start ceremony\n<<requires full setup>>
CeremonyState --> ChoosingWeddingPhaseState : [done]

ChoosingWeddingPhaseState --> PhotoSessionState : 9. Start photos\n<<requires basic setup>>
PhotoSessionState --> ChoosingWeddingPhaseState : [done]

ChoosingWeddingPhaseState --> BanquetState : 10. Start banquet\n<<requires full setup>>
BanquetState --> ChoosingWeddingPhaseState : [done]

ChoosingWeddingPhaseState --> SummarizeState : 11. Summarize
SummarizeState --> [*] : [wedding concluded]


@enduml