@startuml
scale 800 width

[*] --> ChoosingWeddingPhaseState : program starts

state ChoosingWeddingPhaseState {
  [*] --> ChoosingPhase
  ChoosingPhase --> PhaseSelected : selecting phase
}

ChoosingWeddingPhaseState --> CreatingNewlywedState : Choosing option 1
CreatingNewlywedState --> ChoosingWeddingPhaseState : phase's over

ChoosingWeddingPhaseState --> ChoosingWeddingPlaceState : Choosing option 2
ChoosingWeddingPlaceState --> ChoosingWeddingPhaseState : phase's over

ChoosingWeddingPhaseState --> ChoosingFianceeDressState : Choosing option 3
note on link : Requires: Groom, Fiancee
ChoosingFianceeDressState --> ChoosingWeddingPhaseState : phase's over

ChoosingWeddingPhaseState --> ChoosingGroomDressState : Choosing option 4
note on link : Requires: Groom, Fiancee
ChoosingGroomDressState --> ChoosingWeddingPhaseState : phase's over

ChoosingWeddingPhaseState --> ChoosingRingState : Choosing option 5
note on link : Requires: Groom, Fiancee
ChoosingRingState --> ChoosingWeddingPhaseState : phase's over

ChoosingWeddingPhaseState --> ChoosingWeddingMenuState : Choosing option 6
ChoosingWeddingMenuState --> ChoosingWeddingPhaseState : phase's over

ChoosingWeddingPhaseState --> GuestInvitationState : Choosing option 7
GuestInvitationState --> ChoosingWeddingPhaseState : phase's over

ChoosingWeddingPhaseState --> CeremonyState : Choosing option 8
note on link : Requires: Groom, Fiancee, Rings, Suits, Guests, Dishes
CeremonyState --> ChoosingWeddingPhaseState : phase's over

ChoosingWeddingPhaseState --> PhotoSessionState : Choosing option 9
note on link : Requires: Groom, Fiancee, Rings, Suits
PhotoSessionState --> ChoosingWeddingPhaseState : phase's over

ChoosingWeddingPhaseState --> BanquetState : Choosing option 10
note on link : Requires: Groom, Fiancee, Rings, Suits, Guests, Dishes
BanquetState --> ChoosingWeddingPhaseState : phase's over

ChoosingWeddingPhaseState --> SummarizeState : Choosing option 11
note on link : Requires: Groom, Fiancee, Rings, Suits, Guests, Dishes
SummarizeState --> [*] : wedding concluded

@enduml